### ISSUE TITLE
Modifying a Playlist

### ISSUE THREAD

**Issue by BenziDarwin** [Anslem27/Gem-Docs#2]
After creating one, songs can be added to a playlist, but there is no button to remove a song from a playlist. Then after making a playlist, it will not be displayed, maybe if you restart the app or create and delete another playlist.

**Comment by Anslem27** [comment]
@BenziDarwin. Editing a song in a playlist is available.

Just go to the either online or local playlist tab.
Pick a playlist.
Then a page with the list of songs in playlist will appear.
Then you have options to remove the song, as well as other options still bring research on

**Comment by Anslem27** [comment]
For the other create Playlist option, I'll look into it

**Comment by BenziDarwin** [comment]
Thank you, hopefully, did you make a release already?

**Comment by Anslem27** [comment]
This issue has been closed, and slating a new release any time soon.
However all releases, and other gem app docs are soon migrating to this repo: https://github.com/Anslem27/gem-site/issues.

So kindly migrate all issues and inquiries here
